[build]
  command = "CI=false npm run build"
  publish = "dist"

[context.production.environment]
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_VERSION = "22"

[context.deploy-preview.environment]
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_VERSION = "22"

[context.branch-deploy.environment]
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_VERSION = "22"
